export const PRICING_PLANS = [
  {
    name: "Free",
    price: "0",
    currency: "฿",
    period: "/month",
    buttonLabel: "Sign Up Now",
    buttonHref: "#",
    buttonVariant: "bordered" as const,
    recommended: false,
    features: [
      "50 credits/month",
      "Single Workspace",
    ],
  },
  {
    name: "Starter",
    price: "690",
    currency: "฿",
    period: "/month",
    buttonLabel: "Subscribe Now",
    buttonHref: "#",
    buttonVariant: "solid" as const,
    recommended: false,
    features: [
      "150 credits/month",
      "Single Workspace",
      "Export to CSV, XSLX",
    ],
  },
  {
    name: "Plus",
    price: "1,699",
    currency: "฿",
    period: "/month",
    buttonLabel: "Subscribe Now",
    buttonHref: "#",
    buttonVariant: "solid" as const,
    recommended: false,
    features: [
      "400 credits/month",
      "Single Workspace",
      "Export to CSV, XSLX",
      "Advance Agent Custmization",
    ],
  },
  {
    name: "Pro",
    price: "5,990",
    currency: "฿",
    period: "/month",
    buttonLabel: "Subscribe Now",
    buttonHref: "#",
    buttonVariant: "solid" as const,
    recommended: true,
    features: [
      "1,500 credits/month",
      "Team Workspace",
      "Export to CSV, XSLX",
      "Advance Agent Custmization",
      "Community Access",
    ],
  },
  {
    name: "Agency",
    price: "11,999",
    currency: "฿",
    period: "/month",
    buttonLabel: "Subscribe Now",
    buttonHref: "#",
    buttonVariant: "solid" as const,
    recommended: false,
    features: [
      "3,500 credits/month",
      "Team Workspace",
      "Export to CSV, XSLX",
      "Advance Agent Custmization",
      "Community Access",
      "Priority Support",
    ],
  },
];

export const CUSTOM_PLAN_INCLUDES = [
  "Higher or unlimited usage",
  "Multi-market data coverage",
  "Custom integrations",
  "Unlock customizable agent capability",
];

export const PAYMENT_METHODS = [
  "Credit and debit cards",
  "Bank or wire transfer (for eligible plans)",
  "Invoicing available for business accounts",
  "Support for multiple currencies",
];
