export const PRICING_PLANS = [
  {
    name: "Free",
    price: "0",
    currency: "฿",
    period: "/month",
    buttonLabel: "Sign Up Now",
    buttonHref: "#",
    buttonVariant: "bordered" as const,
    benefits: [
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: false },
      { label: "Benefit", included: false },
      { label: "Benefit", included: false },
      { label: "Benefit", included: false },
      { label: "Benefit", included: false },
      { label: "Benefit", included: false },
      { label: "Benefit", included: false },
    ],
  },
  {
    name: "Starter",
    price: "799",
    currency: "฿",
    period: "/month",
    buttonLabel: "Subscribe Now",
    buttonHref: "#",
    buttonVariant: "solid" as const,
    benefits: [
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: false },
      { label: "Benefit", included: false },
      { label: "Benefit", included: false },
      { label: "Benefit", included: false },
    ],
  },
  {
    name: "Professional",
    price: "3,999",
    currency: "฿",
    period: "/month",
    buttonLabel: "Subscribe Now",
    buttonHref: "#",
    buttonVariant: "solid" as const,
    benefits: [
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
      { label: "Benefit", included: true },
    ],
  },
];

export const CUSTOM_PLAN_INCLUDES = [
  "Higher or unlimited usage",
  "Multi-market data coverage",
  "Custom integrations",
  "Dedicated onboarding and support",
];

export const PAYMENT_METHODS = [
  "Credit and debit cards",
  "Bank or wire transfer (for eligible plans)",
  "Invoicing available for business accounts",
  "Support for multiple currencies",
];
