import { Task } from "@/types/task";

export const sampleTasks: Task[] = [
  {
    id: "task-1",
    title: "Q4 Strategy Deck",
    description: "Prepare the final presentation for the marketing team review.",
    status: "todo",
    priority: "high",
    category: "MARKETING",
    tags: ["marketing", "presentation"],
    assignees: [
      { name: "Alex", color: "#f97316" },
      { name: "Sam", color: "#a855f7" },
    ],
    createdAt: new Date("2026-02-20"),
    updatedAt: new Date("2026-02-21"),
    dueDate: new Date("2026-02-23T17:00:00"),
  },
  {
    id: "task-2",
    title: "Sprint Planning Board",
    description: "Set up the sprint board and define acceptance criteria for Q1 goals.",
    status: "todo",
    priority: "medium",
    category: "DEVELOPMENT",
    tags: ["planning"],
    assignees: [
      { name: "Jordan", color: "#3b82f6" },
    ],
    createdAt: new Date("2026-02-19"),
    updatedAt: new Date("2026-02-20"),
  },
  {
    id: "task-3",
    title: "Refactor Auth Flow",
    description: "Move to OAuth2 and simplify the login components.",
    status: "todo",
    priority: "high",
    category: "DEVELOPMENT",
    tags: ["backend", "security"],
    assignees: [
      { name: "Taylor", color: "#22c55e" },
    ],
    createdAt: new Date("2026-02-18"),
    updatedAt: new Date("2026-02-19"),
    dueDate: new Date("2026-11-15"),
  },
  {
    id: "task-4",
    title: "User Interview Recap",
    description: "Summarize the findings from the last 5 user testing sessions.",
    status: "in-progress",
    priority: "high",
    category: "DESIGN",
    tags: ["research", "ux"],
    assignees: [
      { name: "Morgan", color: "#ec4899" },
      { name: "Riley", color: "#6366f1" },
    ],
    createdAt: new Date("2026-02-21"),
    updatedAt: new Date("2026-02-21"),
    isOverdue: true,
  },
  {
    id: "task-5",
    title: "Brand Refresh Concepts",
    description: "Explore three visual directions for the new brand identity.",
    status: "in-progress",
    priority: "medium",
    category: "DESIGN",
    tags: ["branding", "design"],
    assignees: [
      { name: "Casey", color: "#f59e0b" },
    ],
    createdAt: new Date("2026-02-15"),
    updatedAt: new Date("2026-02-18"),
    dueDate: new Date("2026-02-28"),
  },
  {
    id: "task-6",
    title: "Update Team Handbook",
    description: "Added the new remote-work policies.",
    status: "done",
    priority: "low",
    category: "OPERATIONS",
    tags: ["documentation", "hr"],
    assignees: [
      { name: "Drew", color: "#14b8a6" },
    ],
    createdAt: new Date("2026-02-17"),
    updatedAt: new Date("2026-02-18"),
  },
  {
    id: "task-7",
    title: "Launch Email Campaign",
    description: "Schedule and deliver the product update newsletter.",
    status: "done",
    priority: "medium",
    category: "MARKETING",
    tags: ["email", "campaign"],
    assignees: [
      { name: "Alex", color: "#f97316" },
    ],
    createdAt: new Date("2026-02-14"),
    updatedAt: new Date("2026-02-16"),
  },
  {
    id: "task-8",
    title: "Design System Tokens",
    description: "Define color, spacing, and typography tokens for the component library.",
    status: "done",
    priority: "high",
    category: "DESIGN",
    tags: ["design-system"],
    assignees: [
      { name: "Morgan", color: "#ec4899" },
    ],
    createdAt: new Date("2026-02-13"),
    updatedAt: new Date("2026-02-15"),
  },
  {
    id: "task-9",
    title: "Set up CI/CD Pipeline",
    description: "Configure GitHub Actions for automated testing and deployment.",
    status: "done",
    priority: "high",
    category: "DEVELOPMENT",
    tags: ["devops"],
    assignees: [
      { name: "Taylor", color: "#22c55e" },
      { name: "Jordan", color: "#3b82f6" },
    ],
    createdAt: new Date("2026-02-12"),
    updatedAt: new Date("2026-02-14"),
  },
  {
    id: "task-10",
    title: "Accessibility Audit",
    description: "Run an audit on the top 10 pages and document WCAG violations.",
    status: "done",
    priority: "medium",
    category: "OPERATIONS",
    tags: ["a11y", "audit"],
    assignees: [
      { name: "Riley", color: "#6366f1" },
    ],
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-02-12"),
  },
  {
    id: "task-11",
    title: "Onboard New Engineers",
    description: "Prepare dev environment setup guide and schedule walkthroughs.",
    status: "done",
    priority: "low",
    category: "OPERATIONS",
    tags: ["hr", "onboarding"],
    assignees: [
      { name: "Drew", color: "#14b8a6" },
    ],
    createdAt: new Date("2026-02-08"),
    updatedAt: new Date("2026-02-10"),
  },
  {
    id: "task-12",
    title: "Social Media Calendar",
    description: "Plan and schedule posts for March across all platforms.",
    status: "done",
    priority: "low",
    category: "MARKETING",
    tags: ["social", "content"],
    assignees: [
      { name: "Casey", color: "#f59e0b" },
    ],
    createdAt: new Date("2026-02-07"),
    updatedAt: new Date("2026-02-09"),
  },
  {
    id: "task-13",
    title: "Database Schema Migration",
    description: "Migrate legacy tables to the new normalized schema.",
    status: "done",
    priority: "high",
    category: "DEVELOPMENT",
    tags: ["database", "backend"],
    assignees: [
      { name: "Jordan", color: "#3b82f6" },
    ],
    createdAt: new Date("2026-02-06"),
    updatedAt: new Date("2026-02-08"),
  },
];
